CI test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -50,10 +50,13 @@ jobs:
         echo "REDIS_ADDRESS=0.0.0.0:6379" >> app.env
 
     - name: Check if .env exists
-      run: ls -la # | grep app.env || echo "app.env file not found"
+      run: ls -la | grep app.env || echo "app.env file not found" | cat app.env
     
-
-
+    - name: Move config file
+      run: mv app.env /home/runner/work/simple-bank/simple-bank/
+    
+    - name: Debug: Show files
+      run: ls -la
 
     - name: Set up Go
       uses: actions/setup-go@v4
